openapi: 3.0.0
info:
  title: Receipes API ABN
  description: This is a test case for ABN, representing an Receipes API where you can add, edit, delete and search for receipes.
  version: 1.0.0
  contact:
    name: Pedro Ventura
    email: pedro.asventura@gmail.com
servers:
  - url: http://localhost/v1
paths:
  /receipes:
    get:
      summary: Returns a paginated list of Receipes.
      operationId: getReceipes
      description: Endpoint to get all the existent receipes on database
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipes'

components:
  schemas:
    Receipes:
      title: Receipes
      type: object
      properties:
        items:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/Receipe'
        page:
          $ref: '#/components/schemas/Page'
    Page:
      title: Page
      type: object
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
        itemCount:
          type: integer
    Receipe:
      title: Receipe
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Banana Cake
        servings:
          type: integer
        ingredients:
          type: array
          items:
            type: string
      # Both properties are required
      required:
        - id
        - name
